name: 'kpenfound'
description: 'Multiplatform action'
author: 'kpenfound'
inputs:
  path:
    required: true
    description: 'path to a python file'
outputs:
  stdout:
    description: 'stdout from the executed python file'
runs:
  using: 'node16'
  main: 'dist/index.js'
